### ISSUE TITLE
Installation issues related to jax/jaxlib/other dependencies

### ISSUE THREAD

**Issue by iseultj** [jthlab/bmws#1]
Hi, I was trying to install this and ran into a problem with jax/jaxlib - apparently tree_multimap has been deprecated since jax 0.3.5 and was removed in jax 0.3.16. 

I also ran into a few other issues, including:
```
File "programs/bmws/src/bmws/bmws/cli.py", line 155, in bmws_main
	args.func(args)
TypeError: 'ArgumentParser' object is not callable
``` 
(which I was able to get past by just setting it to `analyze` ), and also ran into an issue with importing things from `estimate.py` (which I got around by importing each function individually).

Do you have a conda environment/ docker image or similar to allow people to run this tool? I wasn't sure to what extent these issues just came up because of dependency problems.

Thanks very much!

Iseult

**Comment by terhorst** [comment]
Thanks for the report. I removed the old deprecated Jax code. I wasn't ever able to reproduce the error you got when calling `bmws`, but I did add some tests which verify that the cli is working properly. A Docker image should be easy to set up, I'll have time to work on it next week.

**Comment by iseultj** [comment]
Thanks very much!

**Comment by iseultj** [comment]
Hi, I was just wondering if you had had time to set up a docker image to help with the installation issues? Thanks very much!

**Comment by terhorst** [comment]
Sorry for the delay/thanks for the reminder. `docker run terhorst/bmws` should now work!
