### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by jkreinz** [jthlab/bmws#2]
Hi there,

Thanks for making this program so easy to run! 

I just wanted to check in about the format of the `bmws analyze` output file. The three columns at the end of the file I've ascertained from other scripts in the repo are c("S.HAT", "SL1", "SL2"). I'm guessing s.hat is the mean selection coefficient as in the manuscript, but can you clarify what SL1 and SL2 are (I'm guessing one of them is the RMS)?

Cheers,
Julia

**Comment by mathii** [comment]
Hi Julia, 

Correct, SL1 is the RMS; i.e. sqrt(mean(s(t)^2)) where the mean is over timepoints t, which is what we use in the paper. SL2 is sqrt(mean((s(t)-mean(s(t)))^2)), which was supposed to be a measure of variation about the mean to try to detect selection coefficients that varied over time, but it didn't work that well. 

- Iain

**Comment by jkreinz** [comment]
Thanks very much for the quick response. And for the LCR_data_analysis.py code for reproducing the analyses in Figure 5, I've found the input files (https://github.com/jthlab/bmws/blob/master/paper/data/Britain_LCT.txt) but could you clarify what is expected for column 1 and column 2? 

Cheers,
Julia

**Comment by mathii** [comment]
column 1 is generation, column 2 Is total number of alleles observed, column 3 is number of alternative alleles observed. 

But to run on your own data you're better off just running the bmws command line program on your own vcf files, unless you are bootstrapping confidence intervals, in which case you'd need to code from the notebook. 

- Iain

**Comment by jkreinz** [comment]
Hi Iain,

Sorry, I should have been more clear. I've run the command line program at varying smoothing parameters and with randomized times successfully. I'm looking to extract the skyline plots of the time-varying selection coefficients for particular loci (as you've done in figure 5). For this, I've been referring to the LCT_data_analyis.py. 

Taking a look at the input files for that script, I've found Britain_LCT.txt, but you refer to the input as having three columns, while that file only has two, and neither of the values within those columns are what I would expect for generation or number of alleles observed. 

Thanks for your help and let me know if you rather me move this conversation elsewhere.
Julia

**Comment by mathii** [comment]
Oh right, sorry, yes, there are only two columns (total alleles, alternative alleles), and one row per column (including rows with zero observations). Where do I say there are 3 columns? That's a mistake, I'll fix that. 

If you just want to output the trajectory (i.e. the value of s per generation, without bootstrapping), you can use the -t option in the command line program. 

- Iain
