### ISSUE TITLE
calculate the selection trajectories

### ISSUE THREAD

**Issue by ygaohahaha** [jthlab/bmws#4]
Hello everyone,

I have a question about how to obtain results similar to Figure 5 in the paper. When I test the script with allbrit.vcf.gz and the command line:
bmws analyze allbrit.vcf.gz allbrit.meta -d pseudohaploid -l 4.5 -g 30 -t -o result.txt
I receive results that include per-SNP selection scan results. However, I would like to know how to obtain results with 1000 replicates and confidence intervals based on vcf. Thank you!

**Comment by mathii** [comment]
Hi, the bootstrapping code we used for the examples is in LCT_data_analyis.py (with a slightly different file format). Unfortunately we didn't implement it in the command line version yet, although we should definitely do that. For now, you should just modify the LCT_data_analyis.py script and process your data into that format.

**Comment by ygaohahaha** [comment]
Thanks Iain , i think i got it. now i got a new problem, when i run the bmws with test_data, i could got a correctly result; but when i did it with the other data, it failed. The issue might be caused by an incorrect recognition of the genotype， but I'm not sure where the issue lies. It looks like:

$ bmws analyze aadr.vcf aadr.meta -l 4.5 -d pseudohaploid
Traceback (most recent call last):
  File "/mnt/users/conda/envs/bwms/bin/bmws", line 8, in <module>
    sys.exit(bmws_main())
  File "/mnt/users/conda/envs/bwms/lib/python3.10/site-packages/bmws/cli.py", line 165, in bmws_main
    args.func(args)
  File "/mnt/users/conda/envs/bwms/lib/python3.10/site-packages/bmws/cli.py", line 175, in analyze_data
    obs = gt_to_obs(ids, gt, meta, args.data)
  File "/mnt/users/conda/envs/bwms/lib/python3.10/site-packages/bmws/cli.py", line 156, in gt_to_obs
    raise Exception("Unknown genotype for data\n"+str(gt))
Exception: Unknown genotype for data
[0, 0, 0, 0, 2, 0, 0, 0, 2, 0, 2, 2, 0, 2, 2, 2]

The VCF file was generated from AADR database by eigenstrat2vcf.py ; and the meta file was generated from the AADR anno file. The two files are consistent with the format of the example file. 

##fileformat=VCFv4.0
##source=eigenstrat2vcf.py
##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  I13778  I0231   I0726   I3716   I16256  I14689  I13838  
12      5382654        rs1427685       T       C       100     PASS    .       GT      0/0     0/0     0/0     0/0     1/1     0/0     0/0    

#ID     DateBP  Region  Latitude        Longitude
I17622  3050    Albania 40.295  19.49027778
I19493_in.preparation   2750    Bulgaria        41.73   26.33
I19479_in.preparation   2025    Bulgaria        42.62   25.41
I16326  2625    Czech   Republic        50.291389       14.045556

**Comment by mathii** [comment]
hm, that seems bad, can you post the files (or a minimal example if they're too big).

**Comment by ygaohahaha** [comment]
Thanks Iain,  

I have attached the file here (Due to GitHub restrictions, I added a .txt suffix）
[aEuropean.meta.txt](https://github.com/user-attachments/files/17565343/aEuropean.meta.txt)
[aadr.vcf.txt](https://github.com/user-attachments/files/17565344/aadr.vcf.txt)


$ bmws analyze aadr.vcf  aEuropean.meta -d pseudohaploid -l 4.5 -g 30 -t -o result.txt

**Comment by mathii** [comment]
Oh ok, one of your samples is heterozygous (Ust_Ishim.DG); we don't currently support mixtures of diploid and pseudohaploid data (I suppose no technical reason why we couldn't, but it seems safer not to mix). If you pseudohaploidize that sample it should run. 

I notice that you are trying to run on a very long time series; in general the method is only appropriate for panmictic populations and should not be used when there is extensive admixture, so you should not run it on this set of samples.

**Comment by ygaohahaha** [comment]
Thanks for your  guidance. The script is running smoothly now. Regarding this data, I'm just conducting a test.

Best!
